module.exports = {
	$window: $(window),
	$document: $(document),
	$body: $('body'),
	$cubeItem: $('#cube-slider > .cube-slider__item'),
	$header: $('.header'),
	$sidebar: $('.sidebar'),
	$iContainer: $('.i-container'),
	$pageTitleWrap: $('.page-title-wrap'),
	$pageTitle: $('.page-title'),
	$sidebarFixed: $('.side-fixed'),
	$content: $('.content'),
	$burger: $('.hamburger'),
	$burgerBtn: $('.burger-btn'),
	$popUpBg: $('.pop-up-bg'),
	$filialsTab: $('.filials-tab'),
	$filialTab: $('.filials-tabItem'),
	$filialsContent: $('.filials-content'),
	$filialContent: $('.filials-contentItem'),
	$contactTab: $('.contactsTabItem'),
	$contactContent: $('.contactsContentItem'),
	$sideText: $('.sidebar__text'),
	$pageMask: $('.page-mask'),
	$maskBottom: $('.page-mask.mask-bottom'),
	$sliderWidget: $('.slider-widget'),
	$testimonialsSlider: $('.testimonials-slider'),
	$otherPostContent: $('.other-postsItem-content'),
	$pageModalMenu: $('.page-modal-menu'),
	$headerContacts: $('.header-contacts__current'),
	$roomsFilterLink: $('.rooms-filter .rooms-filterItem__link'),
	$roomsFilterItem: $('.rooms-filter .rooms-filterItem'),
	$cardsItem: $('.cards .cardsItem'),
	$roomGallery: $('.room-gallery'),
	$fancybox: $('[data-fancybox="gallery"]'),
	$moreSwitch: $('#more-switch'),
	$moreWrap: $('#more-wrap'),
	$datepicker: $('.datepicker'),
	$threeGallery: $('.three-gallery'),
	$fourGallery: $('.four-gallery'),
	$tours: $('.tours'),
	$mainMenu: $('.main-menu ul li.dropdown a'),
	$fixBurger: $('.fix-burger'),
	$mobileFixDropdown: $('.mobile-fix-dropdown'),
};
