module.exports = {
	$window: $(window),
	$document: $(document),
	$body: $('body'),
	$cubeItem: $('#cube-slider > .cube-slider__item'),
	$header: $('.header'),
	$sidebar: $('.sidebar'),
	$iContainer: $('.i-container'),
	$pageTitleWrap: $('.page-title-wrap'),
	$pageTitle: $('.page-title'),
	$sidebarFixed: $('.side-fixed'),
	$content: $('.content'),
	$burger: $('.hamburger'),
	$burgerBtn: $('.burger-btn'),
	$popUpBg: $('.pop-up-bg'),
	$filialTab: $('.filials-tabItem'),
	$filialContent: $('.filials-contentItem'),
	$contactTab: $('.contactsTabItem'),
	$contactContent: $('.contactsContentItem'),
	$sideText: $('.sidebar__text'),
	$pageMask: $('.page-mask'),
	$maskBottom: $('.page-mask.mask-bottom'),
	$sliderWidget: $('.slider-widget'),
	$testimonialsSlider: $('.testimonials-slider'),
	$otherPostContent: $('.other-postsItem-content'),
	$pageModalMenu: $('.page-modal-menu'),
	$headerContacts: $('.header-contacts__current')
};
